# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(060005)
$foreground = rgb(F8ECDB)
$color0 = rgb(060005)
$color1 = rgb(312032)
$color2 = rgb(6A3841)
$color3 = rgb(A24556)
$color4 = rgb(AA665A)
$color5 = rgb(7D8983)
$color6 = rgb(B19673)
$color7 = rgb(EDDBC4)
$color8 = rgb(A69989)
$color9 = rgb(412A42)
$color10 = rgb(8E4A57)
$color11 = rgb(D85C73)
$color12 = rgb(E38878)
$color13 = rgb(A7B7AF)
$color14 = rgb(ECC899)
$color15 = rgb(EDDBC4)
