# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EAE9FB
background         #000011
cursor             #B3B0C7

active_tab_foreground     #000011
active_tab_background     #EAE9FB
inactive_tab_foreground   #EAE9FB
inactive_tab_background   #000011

active_border_color   #EAE9FB
inactive_border_color #000011
bell_border_color     #2C3D6A

color0      #10111C
color1		#2C3D6A
color2		#5D5A6F
color3		#5D5A6F
color4		#8A817A
color5		#9390B6
color6		#9390B6
color7		#D9D7F1
color8		#9897A8
color9		#3A518E
color10		#7C7894
color11		#7C7894
color12		#B8ACA2
color13		#C4C0F3
color14		#C4C0F3
color15		#D9D7F1
