# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F0EBE9
background         #000106
cursor             #85AED4

active_tab_foreground     #000106
active_tab_background     #F0EBE9
inactive_tab_foreground   #F0EBE9
inactive_tab_background   #000106

active_border_color   #F0EBE9
inactive_border_color #000106
bell_border_color     #25323E

color0      #000106
color1		#25323E
color2		#13548F
color3		#756758
color4		#5C7997
color5		#5C7997
color6		#A0958F
color7		#E2DAD7
color8		#9E9996
color9		#314253
color10		#1970BF
color11		#9C8975
color12		#7BA2C9
color13		#7BA2C9
color14		#D5C6BF
color15		#E2DAD7
