# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F8ECDB
background         #060005
cursor             #C39B99

active_tab_foreground     #060005
active_tab_background     #F8ECDB
inactive_tab_foreground   #F8ECDB
inactive_tab_background   #060005

active_border_color   #F8ECDB
inactive_border_color #060005
bell_border_color     #312032

color0      #060005
color1		#312032
color2		#6A3841
color3		#A24556
color4		#AA665A
color5		#7D8983
color6		#B19673
color7		#EDDBC4
color8		#A69989
color9		#412A42
color10		#8E4A57
color11		#D85C73
color12		#E38878
color13		#A7B7AF
color14		#ECC899
color15		#EDDBC4
